begin;

create table public.conversations (
    id bigint generated by default as identity primary key,
    paper_id varchar not null
        references public.papers(id) on delete cascade,
    user_id bigint not null
        references public.users(id) on delete cascade,
    title text,
    messages jsonb not null default '[]'::jsonb,
    summary text,
    summarized_through_message_id uuid,
    status text not null default 'idle',
    active_task_id text,
    version bigint not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint conversations_user_paper_unique
        unique (paper_id, user_id),
    constraint conversations_messages_is_array
        check (jsonb_typeof(messages) = 'array'),
    constraint conversations_status_valid
        check (status in ('idle', 'processing', 'failed')),
    constraint conversations_version_nonnegative
        check (version >= 0)
);

comment on table public.conversations is
    'One durable Copilot conversation per DeepRead user and paper.';
comment on column public.conversations.messages is
    'Append-only visible user and assistant messages. System prompts and tool results are not stored here.';
comment on column public.conversations.summary is
    'Rolling inference summary; original messages remain unchanged.';
comment on column public.conversations.summarized_through_message_id is
    'ID of the latest message represented by summary.';
comment on column public.conversations.version is
    'Optimistic concurrency version incremented by every message append.';

create index conversations_user_id_idx
    on public.conversations (user_id);

create index conversations_updated_at_idx
    on public.conversations (updated_at desc);

create unique index conversations_active_task_id_idx
    on public.conversations (active_task_id)
    where active_task_id is not null;

create function public.set_conversation_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.updated_at := now();
    return new;
end;
$$;

revoke all on function public.set_conversation_updated_at() from public;
revoke all on function public.set_conversation_updated_at() from anon;
revoke all on function public.set_conversation_updated_at() from authenticated;

create trigger conversations_set_updated_at
before update on public.conversations
for each row
execute function public.set_conversation_updated_at();

create function public.append_conversation_message(
    p_conversation_id bigint,
    p_message jsonb,
    p_expected_version bigint
)
returns bigint
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_new_version bigint;
begin
    if jsonb_typeof(p_message) is distinct from 'object' then
        raise exception using
            errcode = '22023',
            message = 'conversation message must be a JSON object';
    end if;

    update public.conversations
    set
        messages = messages || jsonb_build_array(p_message),
        version = version + 1
    where id = p_conversation_id
      and version = p_expected_version
    returning version into v_new_version;

    return v_new_version;
end;
$$;

comment on function public.append_conversation_message(bigint, jsonb, bigint) is
    'Atomically appends one message at an expected conversation version. Returns the new version, or NULL on an ID/version mismatch.';

alter table public.conversations enable row level security;

revoke all privileges on table public.conversations from public;
revoke all privileges on table public.conversations from anon;
revoke all privileges on table public.conversations from authenticated;
grant select, insert, update, delete on table public.conversations to service_role;

revoke all privileges on sequence public.conversations_id_seq from public;
revoke all privileges on sequence public.conversations_id_seq from anon;
revoke all privileges on sequence public.conversations_id_seq from authenticated;
grant usage, select on sequence public.conversations_id_seq to service_role;

revoke all on function public.append_conversation_message(bigint, jsonb, bigint) from public;
revoke all on function public.append_conversation_message(bigint, jsonb, bigint) from anon;
revoke all on function public.append_conversation_message(bigint, jsonb, bigint) from authenticated;
grant execute on function public.append_conversation_message(bigint, jsonb, bigint) to service_role;

commit;
